name: elixir

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir:
          [
            "DIR=1.20",
            "DIR=1.20 VARIANT=slim",
            "DIR=1.20 VARIANT=alpine",
            "DIR=1.20 VARIANT=otp-28",
            "DIR=1.20 VARIANT=otp-28-slim",
            "DIR=1.20 VARIANT=otp-28-alpine",
            "DIR=1.20 VARIANT=otp-27",
            "DIR=1.20 VARIANT=otp-27-slim",
            "DIR=1.20 VARIANT=otp-27-alpine",
            "DIR=1.19",
            "DIR=1.19 VARIANT=slim",
            "DIR=1.19 VARIANT=alpine",
            "DIR=1.19 VARIANT=otp-27",
            "DIR=1.19 VARIANT=otp-27-slim",
            "DIR=1.19 VARIANT=otp-27-alpine",
            "DIR=1.19 VARIANT=otp-26",
            "DIR=1.19 VARIANT=otp-26-slim",
            "DIR=1.19 VARIANT=otp-26-alpine",
            "DIR=1.18",
            "DIR=1.18 VARIANT=slim",
            "DIR=1.18 VARIANT=alpine",
            "DIR=1.18 VARIANT=otp-26",
            "DIR=1.18 VARIANT=otp-26-slim",
            "DIR=1.18 VARIANT=otp-26-alpine",
            "DIR=1.18 VARIANT=otp-25",
            "DIR=1.18 VARIANT=otp-25-slim",
            "DIR=1.18 VARIANT=otp-25-alpine",
            "DIR=1.17",
            "DIR=1.17 VARIANT=slim",
            "DIR=1.17 VARIANT=alpine",
            "DIR=1.17 VARIANT=otp-26",
            "DIR=1.17 VARIANT=otp-26-slim",
            "DIR=1.17 VARIANT=otp-26-alpine",
            "DIR=1.17 VARIANT=otp-25",
            "DIR=1.17 VARIANT=otp-25-slim",
            "DIR=1.17 VARIANT=otp-25-alpine",
            "DIR=1.16",
            "DIR=1.16 VARIANT=slim",
            "DIR=1.16 VARIANT=alpine",
            "DIR=1.16 VARIANT=otp-25",
            "DIR=1.16 VARIANT=otp-25-slim",
            "DIR=1.16 VARIANT=otp-25-alpine",
            "DIR=1.16 VARIANT=otp-24",
            "DIR=1.16 VARIANT=otp-24-slim",
            "DIR=1.16 VARIANT=otp-24-alpine",
            "DIR=1.15",
            "DIR=1.15 VARIANT=slim",
            "DIR=1.15 VARIANT=alpine",
            "DIR=1.15 VARIANT=otp-25",
            "DIR=1.15 VARIANT=otp-25-slim",
            "DIR=1.15 VARIANT=otp-25-alpine",
            "DIR=1.15 VARIANT=otp-24",
            "DIR=1.15 VARIANT=otp-24-slim",
            "DIR=1.15 VARIANT=otp-24-alpine"
          ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          ${{ matrix.elixir }}
          git clone https://github.com/docker-library/official-images.git ~/official-images
          cd "$DIR"
          eval $(awk '/ELIXIR_VERSION=/ { sub(/@/, "-", $2); print $2; exit }' ${VARIANT:-.}/Dockerfile)
          image="elixir:${ELIXIR_VERSION#v}${VARIANT:+-$VARIANT}"
          docker build --pull -t "$image" "${VARIANT:-.}"
          ~/official-images/test/run.sh "$image"
          docker images
