name: Nightly Release

on: 
  schedule:
    - cron: "0 */1 * * *" # Every night

jobs:
  delete_previous_nightly: 
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
          ref: main
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true 
          tag_name: main-nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1
        with:
          tag: main-nightly
          allowUpdates: false
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

  prepare_release:
    needs: delete_previous_nightly
    uses: ./.github/workflows/prepare-release.yml
    with:
      version: main-nightly

  publish_pre_release:
    needs: prepare_release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
          ref: main
      - uses: ncipollo/release-action@v1
        with:
          tag: main-nightly
          allowUpdates: true
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
